import Head from "next/head";
import { GetStaticProps } from "next";
import { getLatestNews } from "../services";
import { INews } from "./../models/INews";
import HeadingNews from "../components/HeadingNews";

type Props = {
  newsData: INews[];
};

const Home = ({ newsData }: Props) => {
  const headingNews = newsData && newsData[0];
  return (
    <div className="bg-tertiary">
      <Head>
        <title>Next News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-primary container mx-auto">
        <HeadingNews headingNews={headingNews} />
      </main>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const newsData = await getLatestNews();

  return {
    props: {
      newsData,
    },
  };
};

export default Home;
