import Head from "next/head";
import { GetStaticProps } from "next";
import { getLatestNews } from "../services";
import { INews } from "./../models/INews";
import Image from "next/image";
import { format } from "date-fns";

type Props = {
  newsData: INews[];
};

const Home = ({ newsData }: Props) => {
  const headingNews = newsData && newsData[0];

  return (
    <div className="bg-tertiary">
      <Head>
        <title>Next News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-primary container mx-auto">
        <section
          style={{ maxHeight: "800px" }}
          className="md:h-screen md:relative"
        >
          <div
            style={{ maxHeight: "800px" }}
            className="flex flex-col w-full p-4"
          >
            <Image
              src="https://en.mercopress.com/data/cache/noticias/87777/1000x800/boris-j.jpg"
              layout="responsive"
              objectFit="cover"
              height={500}
              width={500}
              alt="hero"
              priority
            />
          </div>
          <div className="md:absolute -bottom-24 bg-tertiary md:w-4/5 mx-auto inset-x-0 px-4 md:px-10 md:py-8">
            <p>
              {headingNews.author && headingNews.author + " - "}
              {format(new Date(headingNews.published_at), "MMMM dd ,yyyy")}
            </p>
            <h1 className="text-lg md:text-3xl my-4">{headingNews.title}</h1>
            <p>{headingNews.description}</p>
          </div>
        </section>
      </main>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const newsData = await getLatestNews();

  return {
    props: {
      newsData,
    },
  };
};

export default Home;
